import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import "tailwindcss/tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Joi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b from-purple-500 to-pink-500  text-6xl min-h-screen flex flex-col justify-center items-center bg-black text-white">
        <div className="font-mono">Joi</div>
        <p className="text-2xl italic">coming soon</p>
      </main>
    </>
  );
}
